config/routes.rb
David::Application.routes.draw do
  get "main/index"
  get 'main/about'
  root to: 'main#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class='row'>

		<div class="social_links">
			<%= link_to 'https://github.com/presidentJFK' do %>
				<i class="icon-github"></i>
			<% end %>
			
			<a href="mailto:davidmichaelbe@gmail.com?subject=Hello David!">
				<i class="icon-envelope"></i>
			</a>
		</div>
	  
		<h1 class="main_header">David Begin</h1>
	
		<div class="large-10 columns large-centered main_nav">
			<%= link_to 'Work', root_path %> <%= link_to 'About Me', main_about_path %>
		</div>
		
		<div class='large-10 large-centered columns yield_wrapper'>
	  	<%= yield %>
		</div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/main/about.html.erb
<p>
Hello, my name is David Begin. I am 25 year programmer, who has been dabbling in programming since I was a teenager, only to explode into a full blown obssesion with the introduction of Ruby. I have a passion for learning and expanding my knowledge of Technology and Software, whether that be studying the latest concepts in TDD/BDD, trying to improve my vim skills, or learning LISP in my spare time.  
<br />
<br />
I currently freelance, making small to medium sized apps for small businesses, and moving into creating larger Saas Apps. 
</p>

app/views/main/index.html.erb
<div class="image_wrapper">
	<%= image_tag 'dewey3.png' %>
</div>

<div class="large-9 columns large-centered">
	<p>
		The personal page of Ninja/Healer Dewey Nielsen. This was a long maintained blog in Wordpress, that we revived in rails 4, giving it a more modern sleek look. We also exported all of Deweys old Blog posts from Wordpress over to Heroku with Amazon S3 for hosting his pictures.
	</p>

  <%= link_to 'Dewey Nielsen', 'http://dewey-impact.herokuapp.com/' %>
</div>
<hr />




<div class="image_wrapper">
	<%= image_tag 'fitment3.png' %>
</div>

<div class="large-9 columns large-centered">
	<p>
		An clean and minimal e-commerce site written in rails 3. It uses Paypal's API for payments, features full-text search with the use of Solr, and a responsive design. 
	</p>
  <%= link_to 'Fitment Garage', 'http://www.fitmentgarage.com/' %>
</div>
<hr />



<div class="image_wrapper">
	<%= image_tag 'bumble3.png' %>
</div>

<div class="large-9 columns large-centered">
	<p>
		A Blog/E-Commerce site for the Bumble About Honey company. Both selling local Honey and honey accessories, it also keeps track of all the events put on by Bumble about, and the personal blogs of the employees.
	</p>
</div>
<hr />


<div class="image_wrapper">
	<%= image_tag 'patrick3.png' %>
</div>

<div class="large-9 columns large-centered">
	<p>
		Personal Website/Portfolio/Blog/Webstore of local Portland Photographer Patrick Aalto.
	</p>
  <%= link_to 'Aalto Photgraphy', 'http://www.aaltophotography.com/' %>
</div>
<hr />


<div class="image_wrapper">
	<%= image_tag 'ignition3.png' %>
</div>

<div class="large-9 columns large-centered">
	<p>
		A Project Management SaaS Web App, for helping freelance designers keep track of all of their clients, invoices, projects, quotes etc. It uses Braintree's Transparent Re-direct for payments, and keeps users connected to clients not using the email, having email in the app also responding to outside users and emails, and letting those outside users reply in email for users in Ignition. But when they sign up all of their previous conversations are instantly found for you.
	</p>
</div>